name: .NET WinForms Build and Release

on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Zip the Build
        run: zip -r FunDraw ./AppName/bin/Release/netcoreapp3.1/
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.run_number }}
          prerelease: false